# flutter pub get
pub:
	fvm flutter pub get

# ファイル自動生成
gen:
	fvm flutter clean
	fvm flutter pub get
	fvm flutter pub run build_runner build --delete-conflicting-outputs

# build_runner watch
build_runner_watch:
	fvm flutter pub run build_runner watch --delete-conflicting-outputs
