name: ore_chans_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  fl_chart: ^0.63.0
  dio: ^5.3.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  curved_navigation_bar: ^1.0.3
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.2
  riverpod_generator: ^2.3.3
  riverpod_annotation: ^2.1.6
  retrofit: ^4.0.1
  flutter_spinkit: ^5.2.0
  smooth_page_indicator: ^1.1.0
  flutter_gen_runner: ^5.3.2
  flutter_tts: ^3.8.3

flutter_native_splash:
  image: "assets/splash/splash.png"
  color: "#343232"
  fill: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

  min_sdk_android: 21
  cupertino_icons: ^1.0.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.0.4
  logger: ^2.0.2
  pedantic_mono: ^1.24.0+1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  freezed: ^2.4.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - images/photo/
    - assets/images/
