// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4YngXknQemiSem1qZUdJuWjeJMpY1n_g',
    appId: '1:425982312612:web:94a4f94adbd77deb672631',
    messagingSenderId: '425982312612',
    projectId: 'ore-chans-app',
    authDomain: 'ore-chans-app.firebaseapp.com',
    storageBucket: 'ore-chans-app.appspot.com',
    measurementId: 'G-GLMVEW0QYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Y9hCvVA7DoPgkkJA5u5lSWu4MNeVVd4',
    appId: '1:425982312612:android:005970454ecc39f0672631',
    messagingSenderId: '425982312612',
    projectId: 'ore-chans-app',
    storageBucket: 'ore-chans-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5V5TV2RFi8_O7aTWuAVsba5bSJ2Bk3wU',
    appId: '1:425982312612:ios:5675c44356bb65a7672631',
    messagingSenderId: '425982312612',
    projectId: 'ore-chans-app',
    storageBucket: 'ore-chans-app.appspot.com',
    iosBundleId: 'com.example.oreChansApp',
  );
}
